using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace CleanHr.AuthApi.Application.Telemetry;

/// <summary>
/// Provides custom business metrics using System.Diagnostics.Metrics API (OpenTelemetry compatible).
/// HTTP request metrics (duration, status codes) are automatically provided by OpenTelemetry ASP.NET Core instrumentation.
/// Runtime metrics (CPU, memory, GC) are automatically provided by OpenTelemetry Runtime instrumentation.
/// </summary>
public static class ApplicationMetrics
{
    public const string MeterName = "CleanHr.AuthApi.Application";
    private static readonly Meter _meter = new(MeterName, "1.0.0");

    // ===== Business Metrics: Login Operations =====

    /// <summary>
    /// Total number of login attempts categorized by result and error type.
    /// Use this to track business-level login success/failure rates.
    /// </summary>
    public static readonly Counter<long> LoginAttempts = _meter.CreateCounter<long>(
        "auth.login.attempts",
        unit: "{attempt}",
        description: "Total number of login attempts by result and error type");

    /// <summary>
    /// Number of currently active login operations.
    /// Use this to monitor concurrent login load.
    /// </summary>
    public static readonly UpDownCounter<int> ActiveLogins = _meter.CreateUpDownCounter<int>(
        "auth.login.active",
        unit: "{login}",
        description: "Number of currently active login operations");

    // ===== Business Metrics: Token Operations =====

    /// <summary>
    /// Total number of JWT tokens generated categorized by token type (access, refresh).
    /// </summary>
    public static readonly Counter<long> TokensGenerated = _meter.CreateCounter<long>(
        "auth.tokens.generated",
        unit: "{token}",
        description: "Total number of JWT tokens generated by type");

    // ===== Business Metrics: Password Validation =====

    /// <summary>
    /// Total number of password validation attempts categorized by result.
    /// Use this to track password validation success/failure rates.
    /// </summary>
    public static readonly Counter<long> PasswordValidations = _meter.CreateCounter<long>(
        "auth.password.validations",
        unit: "{validation}",
        description: "Total number of password validation attempts by result");

    // ===== Business Metrics: User Lookups =====

    /// <summary>
    /// Total number of user lookup operations categorized by result.
    /// Use this to track user existence checks.
    /// </summary>
    public static readonly Counter<long> UserLookups = _meter.CreateCounter<long>(
        "auth.user.lookups",
        unit: "{lookup}",
        description: "Total number of user lookup operations by result");

    // ===== Helper Methods =====

    /// <summary>
    /// Records a login attempt with the specified result and error type.
    /// </summary>
    public static void RecordLoginAttempt(string result, string errorType = "none")
    {
        var tags = new TagList
        {
            { "result", result },
            { "error_type", errorType }
        };
        LoginAttempts.Add(1, tags);
    }

    /// <summary>
    /// Records a token generation event.
    /// </summary>
    public static void RecordTokenGeneration(string tokenType)
    {
        var tags = new TagList { { "token_type", tokenType } };
        TokensGenerated.Add(1, tags);
    }

    /// <summary>
    /// Records a password validation attempt.
    /// </summary>
    public static void RecordPasswordValidation(bool isValid)
    {
        var tags = new TagList { { "result", isValid ? "success" : "failed" } };
        PasswordValidations.Add(1, tags);
    }

    /// <summary>
    /// Records a user lookup operation.
    /// </summary>
    public static void RecordUserLookup(bool found)
    {
        var tags = new TagList { { "result", found ? "found" : "not_found" } };
        UserLookups.Add(1, tags);
    }
}

